FORMAT: 1A
HOST: http://vueltapapi.bigchange.com.co:8080/api_1.0/

# Vueltap REST API

Documentacion oficial del API RESTFul aplicación Vueltap.

## User Methods [/User/Login]

### Login [PUT]

Logueo de usuarios de Vueltap, verificacion de usuario y contraseña.

Descripción de campos JSON (Request), campos relevantes:

- Body:
    - email: correo de usuario
    - password: contraseña de usuario base64 de la contraseña

Descripción de campos JSON (Response), campos relevantes:

- Body:
    - status: estado de la petición correcta = true en caso de error = false
    - message: mensaje de respuesta
    - response: Objeto JSON de Usuario
        - _id : Id único del usuario
        - email: Email de usuario
        - name: Nombre del usuario
        - lastname: Apellidos del usuario
        - session: Objeto JSON de sesión de usuario:
            - exp_date: fecha de expiración del token
            - token: token (email) de usuario generado para la sesión, el cual se usará en los headers más adelante.
        - type: Tipo de servicio que generará el usuario si es mensajería es (messaging)

+ Request (application/json)

    + Body
    
            {
              "email": "wilmeralzateroman@gmail.com",
              "password": "d2FyMjY2MDQ4OQ=="
            }
        
+ Response 200 (application/json)

    + Body
    
            {
              "status": true,
              "response": {
                "_id": "58703a04e8fa120cf0987c17",
                "email": "wilmeralzateroman@gmail.com",
                "email_confirmation": true,
                "active": true,
                "password": "$2a$10$PzZrli3mfND64ZvLho4GZehHRLQAsHH2QIjUBcwiDVbbbLhfrhZrK",
                "name": "Wilmer",
                "lastname": "Alzate Roman",
                "mobilephone": 3204204615,
                "__v": 0,
                "device": [],
                "stats": {
                  "created_services": 178
                },
                "session": {
                  "exp_date": "2017-05-01T05:00:00.000Z",
                  "token": "wilmeralzateroman@gmail.com"
                },
                "corporate_payment": true,
                "favorites": [],
                "password_recover": {
                  "status": true,
                  "token": "$2a$10$ahwhHkWddBNvBWHMxmJ9HepQVtze42MywEh3pm0zueJmSP4U5akVK"
                },
                "type": "messaging"
              },
              "message": "Autenticado correctamente"
            }

## Address Methods [/GetPriceFromLocations/]

### GetPriceFromLocations [POST]

Metodo que permite obtener el precio dado un arreglo de ubicaciones
[pos A, pos B, pos C, etc ...] donde pos A es el punto de partida y de ahi en adelante
son puntos de entrega. Autenticacion basica. Ejemplo: Authorization: 
'Basic ' + btoa(email + ':' + btoa(password)), el objeto locations  en el body
contiene tanto latitud lat como longitud lon en formato estandar como se obtiene en
Google Maps.

Descripción de campos JSON (Request), campos relevantes:

- Header:
    - type: tipo de usuario que realiza la petición, siempre sera "user"
    - Authorization: Autorización Basica para llamados http
    - token: email del usuario u objeto token que se responde en el objeto session.token en el método login

- Body:
    - type_user: tipo de usuario el cual va a consultar (messaging)
    - insurance_value: valor del seguro, no aplica en este caso.
    - is_roundtrip: indica si el servicio es ida y vuelta, en este caso siempre es false
    - locations: arreglo de ubicaciones donde la primera es el punto de partida (recogida)
    y la segunda es el punto de llegada (entrega).
        - lat: latitud (formato estándar)
        - lon: longitud (formato estándar)
        - name: descripción obtenida del Geocoder de Google a partir de la latitud y la longitud.
        - details: no aplica

Descripción de campos JSON (Response), campos relevantes:

- Body:
    - status: estado de la petición correcta = true en caso de error = false.
    - message: mensaje de respuesta con el valor del servicio.
    - value: valor del servicio.
    - insurance: valor del seguro, no aplica en este caso.
    - duration: Duración aproximada de entrega del pedido, despues de ser tomado por un mensajero.
    - durationValue: Duración aproximada de entrega desde de la ubicacion del mensajero hasta la direccion de entrega.
    - originCity: arreglo en el que se encuentra la latitud y longitud de la ciudad en la cual se realizo el servicio,
    por defecto Bogota D.C
    
+ Request (application/json)

    + Headers
    
            type: user
            Authorization: Basic d2lsbWVyYWx6YXRlcm9tYW5AZ21haWwuY29tOmQyRnlNalkyTURRNE9RPT0=
            token: wilmeralzateroman@gmail.com
    
    + Body
    
            {
                "locations":[
                        {
                            "lat":4.68631596952311,
                            "lon":-74.0528381767905,
                            "name":"AC 100 # 19 - 0 ,Bogotá D.C.,Colombia",
                            "details":""
                        },
                        {
                            "lat":4.60333898674767,
                            "lon":-74.0812170856596,
                            "name":"CL 12 # 15 - 0 ,Bogotá D.C.,Colombia",
                            "details":""
                        }
                ],
                "is_roundtrip": false,
                "insurance_value": 0,
                "type_user": "messaging"
            }

+ Response 200 (application/json)

    + Body
    
            {
              "status": true,
              "message": "Valor a pagar aproximado: $13542.88",
              "value": 13542.88,
              "insurance": 0,
              "duration": "23 min1 min",
              "durationValue": "14040",
              "originCity": [
                "4.68631596952311",
                "-74.0528381767905"
              ]
            }
        


## Address Methods Only Description [/GetPrice/]

### GetPrice [POST]

Metodo que permite obtener el precio dadas dos direcciones. Autenticacion basica. Ejemplo: Authorization: 
'Basic ' + btoa(email + ':' + btoa(password)), el objeto locations  en el body
contiene descripción de la dirección de recogida como la de entrega
Google Maps.

Descripción de campos JSON (Request), campos relevantes:

- Header:
    - type: tipo de usuario que realiza la petición, siempre sera "user"
    - Authorization: Autorización Basica para llamados http
    - token: email del usuario u objeto token que se responde en el objeto session.token en el método login

- Body:
    - type_user: tipo de usuario el cual va a consultar (messaging)
    - insurance_value: valor del seguro, no aplica en este caso.
    - is_roundtrip: indica si el servicio es ida y vuelta, en este caso siempre es false
    - pickup_address: dirección de recogida en formato texto ej: calle 100 19 61
    - delivery_address: dirección de entrega en formato texto ej: calle 70 7 30

Descripción de campos JSON (Response), campos relevantes:

- Body:
    - status: estado de la petición correcta = true en caso de error = false.
    - message: mensaje de respuesta con el valor del servicio.
    - value: valor del servicio.
    - insurance: valor del seguro, no aplica en este caso.
    - duration: Duración aproximada de entrega del pedido, despues de ser tomado por un mensajero.
    - durationValue: Duración aproximada de entrega desde de la ubicacion del mensajero hasta la direccion de entrega.
    - pickupdata: objeto en el que se encuentra la información geocodificada de la direccion en la cual se realizará la recogida del pedido,
    por defecto Bogota D.C
    - deliverydata: objeto en el que se encuentra la información geocodificada de la direccion en la cual se realizará la entrega del pedido,
    por defecto Bogota D.C
    
+ Request (application/json)

    + Headers
    
            type: user
            Authorization: Basic d2lsbWVyYWx6YXRlcm9tYW5AZ21haWwuY29tOmQyRnlNalkyTURRNE9RPT0=
            token: wilmeralzateroman@gmail.com
    
    + Body
    
            {
                "pickup_address": "calle 100 19",
                "delivery_address": "calle 70 7 30",
                "is_roundtrip": false,
                "type_user": "messaging",
                "insurance_value": null
            }

+ Response 200 (application/json)

    + Body
    
            {
                "status": true,
                "message": "Valor a pagar aproximado: $5000",
                "value": 5000,
                "insurance": 0,
                "duration": "1 min1 min",
                "durationValue": "00",
                "pickupdata": {
                    "response": {
                        "type": "Feature",
                        "geometry": {
                            "type": "Point",
                            "coordinates": [
                                -74.0528381767905,
                                4.68631596952311
                            ]
                        },
                        "properties": {
                            "commonName": "AVENIDA CARLOS LLERAS RESTREPO",
                            "country": "co",
                            "address": "AC 100 # 19 - 0 ",
                            "city": "bogota",
                            "postcode": "110111",
                            "accuracy": "line_interpolation",
                            "admin1": "Colombia",
                            "attribution": "geoapps",
                            "admin2": "Bogotá D.C.",
                            "id": null,
                            "admin5": "Santa Bibiana",
                            "admin3": "Bogotá D.C.",
                            "admin4": "Usaquen"
                        }
                    }
                },
                "deliverydata": {
                    "response": {
                        "type": "Feature",
                        "geometry": {
                            "type": "Point",
                            "coordinates": [
                                -74.0570335915839,
                                4.65321519636
                            ]
                        },
                        "properties": {
                            "commonName": null,
                            "country": "co",
                            "address": "CL 70 # 7 - 70 ",
                            "city": "bogota",
                            "postcode": null,
                            "accuracy": "line_interpolation",
                            "admin1": "Colombia",
                            "attribution": "geoapps",
                            "admin2": "Bogotá D.C.",
                            "id": null,
                            "admin5": "Quinta Camacho",
                            "admin3": "Bogotá D.C.",
                            "admin4": "Chapinero"
                        }
                    }
                }
            }




        
## Create Delivery Methods [/DeliveryItem/CreateMultiple/]

### CreateMultiple [POST]
Método de creación de pedidos

Descripción de campos JSON (Request), campos relevantes:

- Header:
    - type: tipo de usuario que realiza la peticion, por defecto "user".
    - Autorizathion: Autorización basica para los llamadas http.
    - token: email del usuario u objeto token que se responde en el objeto session.token en el método login.

- Body:
    - insurancevalue: Valor del seguro, no aplica.
    - insurance: Validación si el servicio viene asegurado, no aplica.
    - insurance_price: Valor del seguro, no aplica.
    - promo_code_id: Codigo de promocion con descuento, obsequiado al usuario, no aplica.
    - discount: Valor del descuento aplicado al codigo de promoción, no aplica.
    - price_to_pay: Valor a pagar del servicio creado, que se obtiene en la respuesta del metodo GetPriceFromLocations.
    - ip_address: Direccion IP desde donde se realiza la petición del servicio.
    - item_name: Nombre del pedido, por defecto "Pedido Ciudad de Mascotas - Nombre de usuario"
    - instructions: (opcional) Instrucciones adicionales para la entrega y transporte del pedido.
    - payment_method: Metodo por el cual se va a pagar el servicio, por defecto "corporate".
    - pickup_object: No aplica. No enviar.
    - delivery_object: No aplica. No enviar.
    - user_info: Objeto JSON de sesion usuario. obtenido en el método del Login.
    - user_id: Id unico del usuario, obtenido en el objeto usuario del método login.
    - service_price: Valor a pagar del servicio creado, que se obtiene en la respuesta del metodo GetPriceFromLocations.
    - token_id: id del token de usuario, presente dentro del objeto usuario session.token.
    - service_type: Tipo de servicio generado el mismo que el tipo de usuario ver Login, para mensajería (messaging)
    - bring_cash: (opcional) Si se debe llevar dinero adicional esto se envia en false.
    - how_much_cash: (opcional) Cuanto dinero adicional debe llevar el mensajero, se envía en 0, si el campo anterior en true, este campo es obligatorio
    - raise_cash: (opcional) el mensajero debe recaudar dinero? envíar en true o false según indicaciones de vueltap,
    - how_much_raise: cuanto dinero debe recaudar el mensajero, enviar en 0 si el parámetro anterior es false, si el campo anterior en true, este campo es obligatorio.
    - locations: Arreglo de direcciones, que comprende el punto de recogida (único) y los puntos de entrega (múltiples)
        - address: cadena de la dirección, previamente verificada por el servicio de GetPriceFromLocations
        - details: (opcional) información adicional relevante que ayude el mensajero a realizar la entrega.
        - lat: latitud de la dirección, previamente verificada por el servicio de GetPriceFromLocations
        - long: longitud de la dirección, previamente verificada por el servicio de GetPriceFromLocations
        - presumed_receptionist_name: (opcional) nombre del destinatario 
        - presumed_receptionist_phone: (opcional) teléfono móvil del destinatario
        - order_number: (opcional) número de orden asociada al pedido origen (número de guía,orden o pedido) de los clientes que se integran.
        - weight: peso del paquete en kilogramos, numerico ejemplo 1, 2, 3, etc..

Descripción de campos JSON (Response), campos relevantes:

- Body:
    - status: estado de la petición correcta = true en caso de error = false.
    - message: mensaje de confirmacion en caso de que el estatus sea true.
    - response: Objeto JSON deliveryItem con la informacion del pedido creado.
        - user_id: Id unico de usuario.
        - user_info: Objeto JSON de sesion de usuario.
        - item_name: Nombre del pedido creado de acuerdo al formato establecido.
        - date_created: Fecha de creación del pedido.
        - instructions: Instrucciones establecidas para la entrega y transporte del pedido.
        - overall_status: Estado general del pedido, cuando el valor es "requested" esta solicitado y esta disponible para ser tomado por un mensajero de Vueltap.
            - Variaciones: 
                - requested: solicitado
                - started : iniciado por un mensajero de vueltap
                - aborted: el mensajero lo tomo pero cancelo la etrega
                - finished: entregado a su destino
        - status: Estado del pedido.
            - Variaciones:
                -  Disponible: disponible para ser tomado por un mensajero
                - Aceptado: Aceptado por un mensajero
                - En Tránsito: En camino al destino
                - Entregado: Entregado al destinatario
                - Regresando: aplica sólo para servicios de ida y vuelta.
                - Regresado: regresado al remitente, aplica sólo para servicios de ida y vuelta.
                - Cancelado: Cancelado por el usuario
                - Rechazado: Cancelado por el mensajero
        - _id: id unico del pedido (DeliveryItem).
        - service_price: Valor del servicio creado.
        - service_type: Tipo de servicio generado el mismo que el tipo de usuario ver Login, para mensajería (messaging)
        - bring_cash: Si se debe llevar dinero adicional esto se envia en false.
        - how_much_cash: Cuanto dinero adicional debe llevar el mensajero, se envía en 0
        - raise_cash: el mensajero debe recaudar dinero? envíar en true o false según indicaciones de vueltap,
        - how_much_raise: cuanto dinero debe recaudar el mensajero, enviar en 0 si el parámetro anterior es false,
        - locations: Arreglo de direcciones, que comprende el punto de recogida (único) y los puntos de entrega (múltiples)
            - address: cadena de la dirección, previamente verificada por el servicio de GetPriceFromLocations
            - details: (opcional) información adicional relevante que ayude el mensajero a realizar la entrega.
            - lat: latitud de la dirección, previamente verificada por el servicio de GetPriceFromLocations
            - long: longitud de la dirección, previamente verificada por el servicio de GetPriceFromLocations
            - type: 1 para recogida, 2 para entrega
            - weight: peso del paquete en kilogramos, numerico ejemplo 1, 2, 3, etc..
            - presumed_receptionist_name: (opcional) nombre del destinatario 
            - presumed_receptionist_phone: (opcional) teléfono móvil del destinatario
            - order_number: (opcional) número de orden asociada al pedido origen (número de guía,orden o pedido) de los clientes que se integran.
            - checkin_date: fecha y hora (ISO Date) del checkin de la entrega.
            - status: estado de la entrega. (delivered, not-delivered, in-process)
            - novelty: descripción de la novedad de entrega si el estado es not-delivered.
            - signed_uploaded: bandera que indica si ya se ha anexado la firma de evidencia de entrega.
            - image_uploaded: bandera que indica si ya se ha anexado la imagen de evidencia de entrega.
            - images: Arreglo de imagenes de evidencia
                - name: nombre del archivo de imagen
                - url: url pública de la imagen (Amazon S3)
                - owner: correo del usuario propietario de la imagen
                - size: tamaño del archivo
                - type: tipo de imagen, 1 para evidencia de entrega
            - signature_object: Objeto de firma
                - status: true si existe
                - signatureB64: basw 64 del archivo de imagen de firma
                - date_created: fecha de creación del objeto firma
            - coordinates: Objeto de tipo 2DSphere, para calculo de ubicación.
        
+ Request (application/json)

    + Headers
    
            type: user
            Authorization: Basic d2lsbWVyYWx6YXRlcm9tYW5AZ21haWwuY29tOmQyRnlNalkyTURRNE9RPT0=
            token: wilmeralzateroman@gmail.com
            
    + Body
    
            {
               "insurancevalue":0,
               "insurance":false,
               "insurance_price":0,
               "promo_code_id":"",
               "discount":0,
               "price_to_pay":13542.88,
               "ip_address":"181.33.139.118",
               "item_name":"Pedido Ciudad de Mascotas - Wilmer Alzate",
               "instructions":"Pedido de snack para perro",
               "payment_method":"corporate",
               "locations":[
                  {
                     "lat":4.68631596952311,
                     "lon":-74.0528381767905,
                     "address":"AC 100 # 19 - 0 ,Bogotá D.C.,Colombia",
                     "details":""
                  },
                  {
                     "lat":4.60333898674767,
                     "lon":-74.0812170856596,
                     "address":"CL 12 # 15 - 0 ,Bogotá D.C.,Colombia",
                     "details":"",
                     "presumed_receptionist_name": "Fulano de Tal",
                     "presumed_receptionist_phone": "3112223344",
                     "order_number": "12345678"
                  }
               ],
               "pickup_object":{
                  "lat":"0.000",
                  "lon":"-0.000"
               },
               "delivery_object":{
                  "lat":"0.000",
                  "lon":"-0.000"
               },
               "user_info":{
                    "password_recover" : {
                        "status" : true,
                        "token" : "$2a$10$GP/cLlWSaXXbhE4pX770gOmK8jDk1./eTZ4ZIEubtREaxGLNwLF4G"
                    },
                    "location" : {
                        "address" : "AC 100 # 19 - 0  Bogotá D.C.",
                        "lat" : "4.68631596952311",
                        "lon" : "-74.0528381767905"
                    },
                    "session" : {
                        "token" : "wilmeralzateroman@gmail.com",
                        "exp_date" : "2018-08-01T05:00:00.000Z"
                    },
                    "city" : "bogota",
                    "favorites" : [ ],
                    "set_catcheable_delivery" : true,
                    "type" : "messaging",
                    "corporate_payment" : true,
                    "step_charging" : false,
                    "show_deliver_info_window" : false,
                    "is_countable_user" : true,
                    "in_black_list" : false,
                    "send_sms_in_creation" : false,
                    "_id" : "5a8c8434ef9ddf018d0d6094",
                    "registration_date" : "2018-02-20T20:25:24.700Z",
                    "email" : "wilmeralzateroman@gmail.com",
                    "email_confirmation" : true,
                    "active" : true,
                    "password" : "$2a$10$Bnqd0xoz32szvdnmpsirSeYJIJHGEyyKWzucIFowiURVVEZaovpu2",
                    "name" : "Wilmer",
                    "lastname" : "Alzate Roman",
                    "mobilephone" : 3185022770,
                    "device" : [ ],
                    "stats" : {
                        "created_services" : 0
                    },
                    "wpn_token" : "cH9Db1GekSU:APA91bHot9BJNqpROHscX6oq6CLXWLRERmahgW554huRusn-qC4nVjZGsuWcs5t5C63V0L1Sr6CT3OMmjUhoJNIqtEdpUjGdQtEA5XxDS4T8A_geBUe6EQBCy6CSsXnDPX0rjigI1Bin",
                    "wpn_endpoint" : "https://fcm.googleapis.com/fcm/send/cWm8LCe9Pkc:APA91bGP2ytyFUULKH3bR84hptIf8UEU6qQprWyY7tYj-2-QnMI6j7dQYY30bxsR-pjmWa-vbvJje6hhMCsxQFdmD7BYT8bVs2fSAyuKDaWa90Rlwr9N4ljul4jB-ffpe9FV-C83fItqjk6nfwG4nNH_WKIUcXLP4w",
                    "wpn_auth" : "4JFiTgsNv7vYRHtAq6GZKQ",
                    "wpn_p256dh" : "BJp9nzb3G0Fbs3U4ORcKD1ELsG9o_6XZvXe6N8eUJjAmTJvp8aA-mUajnA4cXMcrWrf5INyxIShtK9jQ2rJUMac"
               },
               "user_id":"5a8c8434ef9ddf018d0d6094",
               "service_price":13542.88,
               "token_id":"58efdc7919d35624070d0187",
               "service_type": "messaging",
               "bring_cash": false,
               "how_much_cash": 0,
               "raise_cash": false,
               "how_much_raise": 0
               
            }

+ Response 200 (application/json)

    + Body
    
            {
              "status": true,
              "message": "Pedido creado exitosamente.",
              "response": {
                "show_deliver_info": false,
                "insurancevalue": 0,
                "insurance_price": 0,
                "priority": 0,
                "time_to_pickup": "",
                "time_to_deliver": "",
                "declared_value": 0,
                "price_to_pay": 13542.88,
                "is_catcheable_by_messenger": true,
                "checkin_is_required": false,
                "service_price": 13542.88,
                "box_cash": false,
                "locations": [
                  {
                    "lat": 4.68631596952311,
                    "lon": -74.0528381767905,
                    "address": "AC 100 # 19 - 0 ,Bogotá D.C.,Colombia",
                    "details": "",
                    "type": 1,
                    "presumed_receptionist_name": {},
                    "presumed_receptionist_phone": {},
                    "identifier": 0,
                    "is_checkin": false,
                    "status": "in-process",
                    "images": [],
                    "third_delivery_item_id": {},
                    "image_uploaded": false,
                    "signed_uploaded": false,
                    "delivery_receiver": {},
                    "delivery_receiver_name": {},
                    "novelty": {},
                    "third_identifier": 0,
                    "signature_object": {
                      "status": false,
                      "signatureB64": {},
                      "date_created": {}
                    },
                    "coordinates": [
                      -74.0528381767905,
                      4.68631596952311
                    ]
                  },
                  {
                    "lat": 4.60333898674767,
                    "lon": -74.0812170856596,
                    "address": "CL 12 # 15 - 0 ,Bogotá D.C.,Colombia",
                    "details": "",
                    "type": 2,
                    "presumed_receptionist_name": "Fulano de Tal",
                    "presumed_receptionist_phone": "3112223344",
                    "order_number": "12345678",
                    "checkin_date": "",
                    "identifier": 1,
                    "is_checkin": false,
                    "status": "in-process",
                    "images": [],
                    "third_delivery_item_id": {},
                    "image_uploaded": false,
                    "signed_uploaded": false,
                    "delivery_receiver": {},
                    "delivery_receiver_name": {},
                    "novelty": {},
                    "third_identifier": 1,
                    "signature_object": {
                      "status": false,
                      "signatureB64": {},
                      "date_created": {}
                    },
                    "coordinates": [
                      -74.0812170856596,
                      4.60333898674767
                    ]
                  }
                ],
                "trn_ids": [],
                "status_novelty": "false",
                "discount": 0,
                "total_service": 0,
                "bring_cash": false,
                "how_much_cash": 0,
                "raise_cash": false,
                "how_much_raise": 0,
                "countable": true,
                "order_set": [],
                "_id": "5b5b53b7bddb224bb95976c3",
                "user_id": "5a8c8434ef9ddf018d0d6094",
                "code_service": "vg-171",
                "user_info": {
                  "password_recover": {
                    "status": true,
                    "token": "$2a$10$GP/cLlWSaXXbhE4pX770gOmK8jDk1./eTZ4ZIEubtREaxGLNwLF4G"
                  },
                  "location": {
                    "address": "AC 100 # 19 - 0  Bogotá D.C.",
                    "lat": "4.68631596952311",
                    "lon": "-74.0528381767905"
                  },
                  "session": {
                    "token": "wilmeralzateroman@gmail.com",
                    "exp_date": "2018-08-01T05:00:00.000Z"
                  },
                  "city": "bogota",
                  "favorites": [],
                  "set_catcheable_delivery": true,
                  "type": "messaging",
                  "corporate_payment": true,
                  "step_charging": false,
                  "show_deliver_info_window": false,
                  "is_countable_user": true,
                  "in_black_list": false,
                  "send_sms_in_creation": false,
                  "_id": "5a8c8434ef9ddf018d0d6094",
                  "registration_date": "2018-02-20T20:25:24.700Z",
                  "email": "wilmeralzateroman@gmail.com",
                  "email_confirmation": true,
                  "active": true,
                  "password": "$2a$10$Bnqd0xoz32szvdnmpsirSeYJIJHGEyyKWzucIFowiURVVEZaovpu2",
                  "name": "Wilmer",
                  "lastname": "Alzate Roman",
                  "mobilephone": 3185022770,
                  "device": [],
                  "stats": {
                    "created_services": 0
                  },
                  "wpn_token": "cH9Db1GekSU:APA91bHot9BJNqpROHscX6oq6CLXWLRERmahgW554huRusn-qC4nVjZGsuWcs5t5C63V0L1Sr6CT3OMmjUhoJNIqtEdpUjGdQtEA5XxDS4T8A_geBUe6EQBCy6CSsXnDPX0rjigI1Bin",
                  "wpn_endpoint": "https://fcm.googleapis.com/fcm/send/cWm8LCe9Pkc:APA91bGP2ytyFUULKH3bR84hptIf8UEU6qQprWyY7tYj-2-QnMI6j7dQYY30bxsR-pjmWa-vbvJje6hhMCsxQFdmD7BYT8bVs2fSAyuKDaWa90Rlwr9N4ljul4jB-ffpe9FV-C83fItqjk6nfwG4nNH_WKIUcXLP4w",
                  "wpn_auth": "4JFiTgsNv7vYRHtAq6GZKQ",
                  "wpn_p256dh": "BJp9nzb3G0Fbs3U4ORcKD1ELsG9o_6XZvXe6N8eUJjAmTJvp8aA-mUajnA4cXMcrWrf5INyxIShtK9jQ2rJUMac"
                },
                "item_name": "Pedido Ciudad de Mascotas - Wilmer Alzate",
                "date_created": "2018-07-27T17:17:43.042Z",
                "insurance": false,
                "instructions": "Pedido de snack para perro",
                "payment_method": "corporate",
                "overall_status": "requested",
                "status": "available",
                "rated": false,
                "payment_token_id": {},
                "promo_code_id": "",
                "service_type": "messaging",
                "schedule_interval": {},
                "step_count": 1,
                "__v": 0
              }
            }
            




## Update WareHouses Method [/Admin/UpdateWarehouses/diego2029_@hotmail.com]

### UpdateWarehouses/:user_email [PUT]
Método de actualización/creación de bodegas

Descripción de campos JSON (Request), campos relevantes:

- Header:
    - type: tipo de usuario que realiza la peticion, por defecto "user".
    - Autorizathion: Autorización basica para los llamadas http.
    - token: email del usuario u objeto token que se responde en el objeto session.token en el método login.

- Params:
    - user_email: Correo de usuario que realiza la petición.
    
- Body:
    - seller: Arreglo de los sellers (bodegas) a actualizar y/o crear en la base de datos de vueltap
        - shop: nombre único del establecimiento (comercio, seller)
        - contact_name: nombre de la persona contacto del establecimiento (comercio, seller)
        - email_address: dirección de correo de la persona contacto del establecimiento (comercio, seller)
        - address: dirección del establecimiento (comercio, seller)
        - phone_number: número telefónico del establecimiento (comercio, seller)
        - zip_code: zip code del establecimiento (comercio, seller)
        - city: nombre de la ciudad de ubicación del establecimiento (comercio, seller)
        - municipality: nombre del departamento, provinica, del establecimiento (comercio, seller)
        
Descripción de campos JSON (Response), campos relevantes:

- Body:
    - status: Estado de la respuesta true = exitosa, false = error
    - message: en caso de error este parámetro contiene la descripción del error.
    - saved: Arreglo de sellers almacenados y/o actualizados
        - count: cantidad de seller almacenados y/o actualizados
        - shop_saved: Arreglo con los sellers almacenados y/o actualizados
            - shop: equivalente al campo shop enviado en la petición (único)
            - shop_id: identificador único del seller almacenado y/o actualizado al lado de vueltap
    - not_saved: Arreglo que contiene la especificación de los shop (sellers) que no se pudieron almacenar
        - count: cantidad de seller no almacenados y/o no actualizados
        - reason: mensaje que contiene la descripción de la razón del error.
        - shop_not_saved: Areglo que contiene la especificación de los sellers
            - shop: descripción (código único) del seller que no se pudo almacenar y/o actualizar
            - addres: dirección del seller que no se pudo almacenar (esto se retorna porque en la mayoria de los casos se retorna un error porque no se pudo verificar la dirección física del seller)

+ Request (application/json)

    + Headers
    
            type: user
            Authorization: Basic d2lsbWVyYWx6YXRlcm9tYW5AZ21haWwuY29tOmQyRnlNalkyTURRNE9RPT0=
            token: wilmeralzateroman@gmail.com
            
    + Body

            {
                "seller":[
                    {
                    "shop":"DIEGO QUINTERO",
                    "contact_name":"diego quintero loaiza",
                    "email_address":"diego@mail.com",
                    "address":"calle 80 10 60",
                    "phone_number":"123456",
                    "zip_code":"00000",
                    "city":"Bogota",
                    "municipality":"Cundinamarca"
                    },
                    {
                    "shop":"WILMER ALZATE",
                    "contact_name":"wilmer alzate",
                    "email_address":"wilmer@mail.com",
                    "address":"carrera 22 18 28",
                    "phone_number":"123456",
                    "zip_code":"00000",
                    "city":"Bogota",
                    "municipality":"Cundinamarca"
                    },
                    {
                    "shop":"DIEGO ESCOBAR",
                    "contact_name":"diego escobar",
                    "email_address":"diego@mail.com",
                    "address":"carrera 2 88",
                    "phone_number":"123456",
                    "zip_code":"00000",
                    "city":"Bogota",
                    "municipality":"Cundinamarca"
                    },
                    {
                    "shop":"CAMILO ARANGO",
                    "contact_name":"camilo arango",
                    "email_address":"camilo@mail.com",
                    "address":"carrera 22 18 28",
                    "phone_number":"123456",
                    "zip_code":"00000",
                    "city":"Bogota",
                    "municipality":"Cundinamarca"
                    }
                ]
            }


+ Response 200 (application/json)

        {
        "status":true,
        "message":"Proceso finalizado",
        "response":{
                "saved":{
                    "count":3,
                    "shop_saved":[
                        {
                        "shop":"DIEGO QUINTERO",
                        "shop_id":"1"
                        },
                        {
                        "shop":"WILMER ALZATE",
                        "shop_id":"2"
                        },
                        {
                        "shop":"CAMILO ARANGO",
                        "shop_id":"3"
                        }
                    ]
                },
                "not_saved":{
                    "count":1,
                    "reason":"Address is not valid. Can't verify address for shop.",
                    "shop_not_saved":[
                        {
                        "shop":"DIEGO ESCOBAR",
                        "address":"carrera 2 88"
                        }
                    ]
                }
            }
        }

            
## Delivery Methods [/DeliveryItem/5b5b53b7bddb224bb95976c3/]

### DeliveryItem/:id [GET]
Obtener detalle de pedido

Descripción de campos JSON (Request), campos relevantes:

- Header:
    - type: tipo de usuario que realiza la peticion, por defecto "user".
    - Autorizathion: Autorización basica para los llamadas http.
    - token: email del usuario u objeto token que se responde en el objeto session.token en el método login.

Descripción de campos JSON (Response), campos relevantes:

- Body:
    - status:
    - response: Objeto JSON de deliveryItem.
        - _id: Id unico del deliveryItem.
        - user_id: Id unico del usuario.
        - user_info: Objeto JSON de sesion usuario.
        - item_name: Nombre del pedido con el formato establecido.
        - date_created: Fecha de creación del pedido.
        - instructions: Instrucciones establecidas para la entrega y transporte del pedido.
        - overall_status: Estado general del pedido, cuando el valor es "requested" esta solicitado y esta disponible para ser tomado por un mensajero de Vueltap.
            - Variaciones: 
                - requested: solicitado
                - started : iniciado por un mensajero de vueltap
                - aborted: el mensajero lo tomo pero cancelo la etrega
                - finished: entregado a su destino
        - status: Estado del pedido.
            - Variaciones:
                -  Disponible: disponible para ser tomado por un mensajero
                - Aceptado: Aceptado por un mensajero
                - En Tránsito: En camino al destino
                - Entregado: Entregado al destinatario
                - Regresando: aplica sólo para servicios de ida y vuelta.
                - Regresado: regresado al remitente, aplica sólo para servicios de ida y vuelta.
                - Cancelado: Cancelado por el usuario
                - Rechazado: Cancelado por el mensajero
        - locations: arreglo de ubicaciones donde la primera es el punto de partida (recogida)
        y la segunda es el punto de llegada (entrega).
            - lat: latitud (formato estándar)
            - lon: longitud (formato estándar)
            - address: descripción obtenida del Geocoder de Google a partir de la latitud y la longitud.
            - details: no aplica.
        - service_price: Valor a pagar del servicio creado.
        - service_type: Tipo de servicio generado mensajería (messaging)
        - bring_cash: se debe llevar dinero adicional, false
        - how_much_cash: Cuento dinero adicional debe llevar el mensajero 0

+ Request (application/json)

    + Headers
    
            type: user
            Authorization: Basic d2lsbWVyYWx6YXRlcm9tYW5AZ21haWwuY29tOmQyRnlNalkyTURRNE9RPT0=
            token: wilmeralzateroman@gmail.com


+ Response 200 (application/json)

    + Body
    
            {
              "status": true,
              "response": {
                "show_deliver_info": false,
                "insurancevalue": 0,
                "insurance_price": 0,
                "priority": 0,
                "time_to_pickup": "",
                "time_to_deliver": "",
                "declared_value": 0,
                "price_to_pay": 13542.88,
                "is_catcheable_by_messenger": true,
                "checkin_is_required": false,
                "service_price": 13542.88,
                "box_cash": false,
                "locations": [
                  {
                    "lat": 4.68631596952311,
                    "lon": -74.0528381767905,
                    "address": "AC 100 # 19 - 0 ,Bogotá D.C.,Colombia",
                    "details": "",
                    "type": 1,
                    "presumed_receptionist_name": {},
                    "presumed_receptionist_phone": {},
                    "identifier": 0,
                    "is_checkin": false,
                    "status": "in-process",
                    "images": [],
                    "third_delivery_item_id": {},
                    "image_uploaded": false,
                    "signed_uploaded": false,
                    "delivery_receiver": {},
                    "delivery_receiver_name": {},
                    "novelty": {},
                    "third_identifier": 0,
                    "signature_object": {
                      "status": false,
                      "signatureB64": {},
                      "date_created": {}
                    },
                    "coordinates": [
                      -74.0528381767905,
                      4.68631596952311
                    ]
                  },
                  {
                    "lat": 4.60333898674767,
                    "lon": -74.0812170856596,
                    "address": "CL 12 # 15 - 0 ,Bogotá D.C.,Colombia",
                    "details": "",
                    "type": 2,
                    "presumed_receptionist_name": "Fulano de Tal",
                    "presumed_receptionist_phone": "3112223344",
                    "order_number": "12345678",
                    "checkin_date": "",
                    "identifier": 1,
                    "is_checkin": false,
                    "status": "in-process",
                    "images": [],
                    "third_delivery_item_id": {},
                    "image_uploaded": false,
                    "signed_uploaded": false,
                    "delivery_receiver": {},
                    "delivery_receiver_name": {},
                    "novelty": {},
                    "third_identifier": 1,
                    "signature_object": {
                      "status": false,
                      "signatureB64": {},
                      "date_created": {}
                    },
                    "coordinates": [
                      -74.0812170856596,
                      4.60333898674767
                    ]
                  }
                ],
                "trn_ids": [],
                "status_novelty": "false",
                "discount": 0,
                "total_service": 0,
                "bring_cash": false,
                "how_much_cash": 0,
                "raise_cash": false,
                "how_much_raise": 0,
                "countable": true,
                "order_set": [],
                "_id": "5b5b53b7bddb224bb95976c3",
                "user_id": "5a8c8434ef9ddf018d0d6094",
                "code_service": "vg-171",
                "user_info": {
                  "password_recover": {
                    "status": true,
                    "token": "$2a$10$GP/cLlWSaXXbhE4pX770gOmK8jDk1./eTZ4ZIEubtREaxGLNwLF4G"
                  },
                  "location": {
                    "address": "AC 100 # 19 - 0  Bogotá D.C.",
                    "lat": "4.68631596952311",
                    "lon": "-74.0528381767905"
                  },
                  "session": {
                    "token": "wilmeralzateroman@gmail.com",
                    "exp_date": "2018-08-01T05:00:00.000Z"
                  },
                  "city": "bogota",
                  "favorites": [],
                  "set_catcheable_delivery": true,
                  "type": "messaging",
                  "corporate_payment": true,
                  "step_charging": false,
                  "show_deliver_info_window": false,
                  "is_countable_user": true,
                  "in_black_list": false,
                  "send_sms_in_creation": false,
                  "_id": "5a8c8434ef9ddf018d0d6094",
                  "registration_date": "2018-02-20T20:25:24.700Z",
                  "email": "wilmeralzateroman@gmail.com",
                  "email_confirmation": true,
                  "active": true,
                  "password": "$2a$10$Bnqd0xoz32szvdnmpsirSeYJIJHGEyyKWzucIFowiURVVEZaovpu2",
                  "name": "Wilmer",
                  "lastname": "Alzate Roman",
                  "mobilephone": 3185022770,
                  "device": [],
                  "stats": {
                    "created_services": 0
                  },
                  "wpn_token": "cH9Db1GekSU:APA91bHot9BJNqpROHscX6oq6CLXWLRERmahgW554huRusn-qC4nVjZGsuWcs5t5C63V0L1Sr6CT3OMmjUhoJNIqtEdpUjGdQtEA5XxDS4T8A_geBUe6EQBCy6CSsXnDPX0rjigI1Bin",
                  "wpn_endpoint": "https://fcm.googleapis.com/fcm/send/cWm8LCe9Pkc:APA91bGP2ytyFUULKH3bR84hptIf8UEU6qQprWyY7tYj-2-QnMI6j7dQYY30bxsR-pjmWa-vbvJje6hhMCsxQFdmD7BYT8bVs2fSAyuKDaWa90Rlwr9N4ljul4jB-ffpe9FV-C83fItqjk6nfwG4nNH_WKIUcXLP4w",
                  "wpn_auth": "4JFiTgsNv7vYRHtAq6GZKQ",
                  "wpn_p256dh": "BJp9nzb3G0Fbs3U4ORcKD1ELsG9o_6XZvXe6N8eUJjAmTJvp8aA-mUajnA4cXMcrWrf5INyxIShtK9jQ2rJUMac"
                },
                "item_name": "Pedido Ciudad de Mascotas - Wilmer Alzate",
                "date_created": "2018-07-27T17:17:43.042Z",
                "insurance": false,
                "instructions": "Pedido de snack para perro",
                "payment_method": "corporate",
                "overall_status": "requested",
                "status": "available",
                "rated": false,
                "payment_token_id": {},
                "promo_code_id": "",
                "service_type": "messaging",
                "schedule_interval": {},
                "step_count": 1,
                "__v": 0
              }
            }
 
## Delivery Trace Methods [/DeliveryTrace/5a38feb7663dcd0e6c246ab7/]  

### DeliveryTrace/:delivery_id [GET]
Obtener trazabilidad de estados

Descripción de campos JSON (Request), campos relevantes:

- Header:
    - type: tipo de usuario que realiza la peticion, por defecto "user".
    - Autorizathion: Autorización basica para los llamadas http.
    - token: email del usuario u objeto token que se responde en el objeto session.token en el método login.


- Params:
    - delivery_id: ide del servicio

Descripción de campos JSON (Response), campos relevantes:

- Body:
Arreglo de estados
    - _id: identificador unico del registro del estado en la base de datos
    - delivery_id: identificador del servicio al que pertenece el estado
    - status: estado del servicio, pueden ser:
        - available: disponbile para ser aceptado por un mensajero
        - accepted: el mensajero lo acepto en la aplicación móvil
        - collected: el mensajero ya recolecto el producto a entregar
        - in-transit: en transito hacia direcciones de entrega.
        - returning: cuando el servicio representa ida y vuelta, es el estado que indica que el mensajero está retornando al punto de partida, sitio de recolección
        - delivered: entregado        
    - overall_status: estado en general del servicio, es para uso interno
        - requested: solicitado por el usuario
        - started: iniciado por el mensajero
        - in-process: en proceso de entrega
        - finished: finalizado/entregado
        - not-deliverd: no entregado, sucedió una novedad al entregar
    - date: fecha y hora (ISO) en la que se registra el movimiento, fecha en que se registro el estado

+ Request (application/json)

    + Headers
    
            type: user
            Authorization: Basic d2lsbWVyYWx6YXRlcm9tYW5AZ21haWwuY29tOmQyRnlNalkyTURRNE9RPT0=
            token: wilmeralzateroman@gmail.com
            

+ Response 200 (application/json)

    + Body
    
            [
                {
                    "_id":"5a57d9c8cce1967b70a65e57",
                    "delivery_id":"5a38feb7663dcd0e6c246ab7",
                    "status":"accepted",
                    "overall_status":"started",
                    "__v":0,
                    "date":"2018-01-11T21:40:24.720Z"
                },
                {
                    "_id":"5a57d9d0cce1967b70a65e58",
                    "delivery_id":"5a38feb7663dcd0e6c246ab7",
                    "status":"available",
                    "overall_status":"requested",
                    "__v":0,
                    "date":"2018-01-11T21:40:32.567Z"
                },
                {
                    "_id":"5a57d9e0cce1967b70a65e59",
                    "delivery_id":"5a38feb7663dcd0e6c246ab7",
                    "status":"accepted",
                    "overall_status":"started",
                    "__v":0,
                    "date":"2018-01-11T21:40:48.655Z"
                },
                {
                    "_id":"5a57d9e6cce1967b70a65e5a",
                    "delivery_id":"5a38feb7663dcd0e6c246ab7",
                    "status":"in-transit",
                    "overall_status":"started",
                    "__v":0,
                    "date":"2018-01-11T21:40:54.254Z"
                },
                {
                    "_id":"5a57d9eccce1967b70a65e5b",
                    "delivery_id":"5a38feb7663dcd0e6c246ab7",
                    "status":"delivered",
                    "overall_status":"finished",
                    "__v":0,
                    "date":"2018-01-11T21:41:00.555Z"
                }
            ]
            
            
## Delivery Create In [/Delivery/CreateDeliveriesByJson]  

### CreateDeliveriesByJson [POST]


Método de creación de pedidos pertenecientes a multiples bodegas (MULTI BODEGA)

Descripción de campos JSON (Request), campos relevantes:

- Header:
    - type: tipo de usuario
    - Authorization: parámetros de usuario y clave en formato Basic
    - token: email del usuario que realiza la petición
    
- Body:
    - city: ciudad en la que se realizaran los servicios, si no se recibe se toma como bogotá.
    - is_roundtrip: describe si el servicio es ida y regreso, si no se recibe valor se toma como false.
    - insurance_amount: valor por el cual quiere asegurar los pedidos, si no se recibe el valor se toma como cero(0).
    - addresses: arreglo con las direcciones de entrega.
        - shop_id: identificador unico de la bodega donde se debe recoger el pedido.
        - direccion: dirección de entrega del pedido.
        - peso: peso del producto a entregar.
        - instrucciones: datos adicionales para la entrega (Apto No, Edificio, ect).
        - orden_numero: descripcion de numero de factura u orden.
        - contacto: nombre de la persona quien posiblemente recibirá el pedido.
        - telefono: número de telefono de quien posiblemente recibirá el pedido.
        - email: correo electrónico de quien posiblemente recibirá el pedido.
    
+ Request (application/json)

    + Headers
    
            type: user
            Authorization: Basic d2lsbWVyYWx6YXRlcm9tYW5AZ21haWwuY29tOmQyRnlNalkyTURRNE9RPT0=
            token: wilmeralzateroman@gmail.com
            
    + Body
    
            {
                "city": "bogota",
                "is_roundtrip": false,
                "insurance_amount": "1000000",
                "addresses": [
                    {
                        "shop_id": "1",
                        "direccion": "Calle 125 #52A-17",
                        "peso": "",
                        "instrucciones": "",
                        "orden_numero": "",
                        "contacto": "Paulina Muñoz",
                        "telefono": "965847147",
                        "email": "paulinamunoz@ejemplo.com"
                    },
                    {
                        "shop_id": "2",
                        "direccion": "Calle 115 #48-1",
                        "peso": "",
                        "instrucciones": "Watch out with the dog!",
                        "orden_numero": "4",
                        "contacto": "Diego Quintero",
                        "telefono": "3114295150",
                        "email": "davidrosales@ejemplo.com"
                    },
                    {
                        "shop_id": "3",
                        "direccion": "Carrera 13 Bis #109-2",
                        "peso": "",
                        "instrucciones": "",
                        "orden_numero": "",
                        "contacto": "Wilmer Alzate",
                        "telefono": "",
                        "email": "sergeaguilera@example.com"
                    },
                    {
                        "shop_id": "3",
                        "direccion": "Calle 2a #69f-2",
                        "peso": "",
                        "instrucciones": "7th floor",
                        "orden_numero": "6",
                        "contacto": "Lucas Uribe",
                        "telefono": "",
                        "email": "lucasuribe@ejemplo.com"
                    },
                    {
                        "shop_id": "1",
                        "direccion": "Calle 39g Sur #68g-1",
                        "peso": "",
                        "instrucciones": "",
                        "orden_numero": "",
                        "contacto": "Al Olatte",
                        "telefono": "",
                        "email": "alolatte@ejemplo.com"
                    }
                ]
            }

+ Response 200 (application/json)

    + Body
    
            {
                "status": true,
                "message": "Proceso finalizado!",
                "response": {
                    "service_create": 3,
                    "total_not_create": 0,
                    "service_not_create": []
                }
            }